server:
  port: 10016

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:10017/despachos_db
    username: discoveryteam
    password: discoveryteam
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: DespachosHikariPool
      connection-test-query: select 1
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect

providers:
  tcc:
    url: http://localhost:10018/
  coordinadora:
    url: http://localhost:10019/

mocks:
  enabled: false
  services:
    tcc:
      enabled: false
      port: 10018
      resources-path: wiremock/tcc
    coordinadora:
      enabled: false
      port: 10019
      resources-path: wiremock/coordinadora

cron:
  pending_shipping: "*/5 * * * * *"
